# tigerml/eda/pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tigerml-eda"
dynamic = ["version"]
description = "TigerML EDA"
license = "LicenseRef-Proprietary"
readme = "README.md"

requires-python = ">=3.10, <3.13"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent"
]

dependencies = [
	"tigerml.core==0.5.0",
	"ruptures==1.1.9",
	# "luminol @ git+https://github.com/linkedin/luminol",
]

[project.urls]
Homepage = "https://docs.tigeranalytics.com/tiger-accelerators/dsml-accelerators/TigerML/latest/"
Repository = "https://git.tigeranalytics.com/tiger-accelerators/dsml-accelerators/TigerML"

[tool.setuptools]
package-dir = {"tigerml.eda" = "."}
packages = [
    "tigerml.eda",
    "tigerml.eda.plotters",
	"tigerml.eda.plotters.feature_analysis",
	"tigerml.eda.plotters.feature_interactions",
	"tigerml.eda.plotters.health_analysis",
	"tigerml.eda.plotters.key_drivers",
	"tigerml.eda.plotters.time_series"
]

[tool.setuptools.dynamic.version]
attr = "config.VERSION"
