# tigerml/pyspark/core/pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tigerml-pyspark-core"
dynamic = ["version"]
description = "TigerML Pyspark Core"
license = "LicenseRef-Proprietary"
readme = "README.md"

requires-python = ">=3.10, <3.13"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent"
]

dependencies = [
	"tigerml.core==0.5.0",
    "pyspark==3.5.5",
    "cytoolz==1.0.1",
    "pyspark-dist-explore==0.1.8",
    "py4j==0.10.9.7"
]

[project.urls]
Homepage = "https://docs.tigeranalytics.com/tiger-accelerators/dsml-accelerators/TigerML/latest/"
Repository = "https://git.tigeranalytics.com/tiger-accelerators/dsml-accelerators/TigerML"

[tool.setuptools]
package-dir = {"tigerml.pyspark.core" = "."}
packages = [
    "tigerml.pyspark.core",
]

[tool.setuptools.dynamic.version]
attr = "config.VERSION"
