# tigerml/model_eval/pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tigerml-model_eval"
dynamic = ["version"]
description = "TigerML Model Evaluation"
license = "LicenseRef-Proprietary"
readme = "README.md"

requires-python = ">=3.10, <3.13"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent"
]

dependencies = [
	"tigerml.core==0.5.0",
	"shap==0.45.1",
	"statsmodels==0.14.2",
]

[project.urls]
Homepage = "https://docs.tigeranalytics.com/tiger-accelerators/dsml-accelerators/TigerML/latest/"
Repository = "https://git.tigeranalytics.com/tiger-accelerators/dsml-accelerators/TigerML"

[tool.setuptools]
package-dir = {"tigerml.model_eval" = "."}
packages = [
    "tigerml.model_eval",
    "tigerml.model_eval.plotters",
	"tigerml.model_eval.plotters.evaluation"
]

[tool.setuptools.dynamic.version]
attr = "config.VERSION"
