channels:
- conda-forge
dependencies:
- six==1.17.0
- mlflow==3.1.1
- arviz==0.21.0
- pyomo==6.9.2
- xmltodict==0.14.2
- pip:
  - tensorflow==2.19.0
  - tensorflow-probability==0.25.0
  - protobuf==5.29.5
