# tigerml/automl/pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tigerml-automl"
dynamic = ["version"]
description = "TigerML Automl"
license = "LicenseRef-Proprietary"
readme = "README.md"

requires-python = ">=3.10, <3.13"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent"
]

dependencies = [
	"tigerml.core==0.5.0",
	"deap==1.4.3",
	"tpot==0.12.2",
    "mxtheme==0.3.17",
    "holidays==0.76",
    "fabric==2.7.1",
    "patchwork==1.0.1", # patchwork #NOTE: if patch work is not installable from pypi.org, use conda-forge instead
    "prophet==1.1.7",
]

[project.urls]
Homepage = "https://docs.tigeranalytics.com/tiger-accelerators/dsml-accelerators/TigerML/latest/"
Repository = "https://git.tigeranalytics.com/tiger-accelerators/dsml-accelerators/TigerML"

[tool.setuptools]
package-dir = {"tigerml.automl" = "."}
packages = [
    "tigerml.automl",
    "tigerml.automl.backends",
    "tigerml.automl.backends._old_ts_algos",
    "tigerml.automl.backends._old_ts_algos.ts_algos",
    "tigerml.automl.backends.ts_algos",
    "tigerml.automl.custom_configs",
    "tigerml.automl.custom_configs.classification",
    "tigerml.automl.custom_configs.regression"
]

[tool.setuptools.dynamic.version]
attr = "config.VERSION"

[tool.setuptools.package-data]
"tigerml.automl.backends" = [
	"conf.json"
]
